// Import and re-export types from schemas
import type {
  FeatureEffectType,
  EffectSource,
  ProficiencyGrant,
  SpellSchool,
  Resistance,
  AbilityFeatureEffect,
  AttributeBoostFeatureEffect,
  StatBonusFeatureEffect,
  ProficiencyFeatureEffect,
  SpellSchoolFeatureEffect,
  SpellSchoolChoiceFeatureEffect,
  UtilitySpellsFeatureEffect,
  SpellTierAccessFeatureEffect,
  ResourceFeatureEffect,
  SubclassChoiceFeatureEffect,
  PickFeatureFromPoolFeatureEffect,
  ResistanceFeatureEffect,
  FeatureEffect,
} from "../schemas/feature-effects";

export type {
  FeatureEffectType,
  EffectSource,
  ProficiencyGrant,
  SpellSchool,
  Resistance,
  AbilityFeatureEffect,
  AttributeBoostFeatureEffect,
  StatBonusFeatureEffect,
  ProficiencyFeatureEffect,
  SpellSchoolFeatureEffect,
  SpellSchoolChoiceFeatureEffect,
  UtilitySpellsFeatureEffect,
  SpellTierAccessFeatureEffect,
  ResourceFeatureEffect,
  SubclassChoiceFeatureEffect,
  PickFeatureFromPoolFeatureEffect,
  ResistanceFeatureEffect,
  FeatureEffect,
};
